export const ADD_TODOS_REQUEST = "ADD_TODOS_REQUEST"
export const ADD_TODOS_SUCCESS = "ADD_TODOS_SUCCESS"
export const ADD_TODOS_FALIURE = "ADD_TODOS_FALIURE"

export const UPDATE_TODOS = "UPDATE_TODOS"
